"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {Environment,PerspectiveCamera,Text} from "@react-three/drei";
import {Physics,RigidBody} from "@react-three/rapier";
import {useEffect,useMemo,useRef,useState} from "react";
import * as THREE from "three";
type Mission={id:string;title:string;reward:string;xp:number;description:string};
const missions:Mission[]=[{id:"first-day",title:"First Day in Lagos",reward:"2500",xp:100,description:"Find your first street contact."},{id:"food-run",title:"Food Delivery",reward:"15000",xp:250,description:"Deliver a food order before traffic wins."},{id:"industrial",title:"Industrial Delivery",reward:"2500000",xp:1200,description:"Take the logistics contract to the refinery district."}];
function Building({x,z,h=8,w=5,d=5}:{x:number;z:number;h?:number;w?:number;d?:number}){return <group position={[x,h/2,z]}><mesh castShadow><boxGeometry args={[w,h,d]}/><meshStandardMaterial color="#68736f"/></mesh></group>}
function Refinery(){return <group position={[28,0,-55]}><Text position={[0,12,0]} fontSize={2.1} color="#f2c94c" anchorX="center">FICTIONAL REFINERY ZONE</Text><mesh position={[0,5,0]} castShadow><cylinderGeometry args={[5,5,10,24]}/><meshStandardMaterial color="#8b9690" metalness={.5} roughness={.4}/></mesh><mesh position={[8,3,-3]} castShadow><cylinderGeometry args={[2,2,6,20]}/><meshStandardMaterial color="#a7aaa2" metalness={.45}/></mesh>{[[-7,2,0],[7,2,5],[0,2,8]].map((p,i)=><mesh key={i} position={p as [number,number,number]} rotation={[0,0,Math.PI/2]} castShadow><cylinderGeometry args={[.45,.45,14,12]}/><meshStandardMaterial color="#c0a84a" metalness={.4}/></mesh>)}</group>}
function World({night}:{night:boolean}){const blocks=useMemo(()=>Array.from({length:34},(_,i)=>({x:(i%2?-1:1)*(10+(i%5)*6),z:-70+Math.floor(i/2)*9,h:5+(i%7)*2})),[]);return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[180,180]}/><meshStandardMaterial color={night?"#17201d":"#5d6a62"}/></mesh><mesh position={[0,.02,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[10,120]}/><meshStandardMaterial color="#202525"/></mesh>{blocks.map((b,i)=><Building key={i}{...b}/>)}<Refinery/><Text position={[0,.2,30]} rotation={[-Math.PI/2,0,0]} fontSize={1.5} color="#e9dfbf">YABA MARKET DISTRICT</Text></group>}
function Player(){const ref=useRef<any>(null);const keys=useRef<Record<string,boolean>>({});useEffect(()=>{const d=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=true,u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;window.addEventListener("keydown",d);window.addEventListener("keyup",u);return()=>{window.removeEventListener("keydown",d);window.removeEventListener("keyup",u)}},[]);useFrame((_,delta)=>{if(!ref.current)return;const k=keys.current;const x=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),z=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0);const v=new THREE.Vector3(x,0,z);if(v.lengthSq()){v.normalize().multiplyScalar((k.shift?11:6)*Math.min(delta,.05));const p=ref.current.translation();ref.current.setNextKinematicTranslation({x:p.x+v.x,y:p.y,z:p.z+v.z})}});return <RigidBody ref={ref} type="kinematicPosition" position={[0,1,12]} colliders="cuboid"><mesh castShadow><capsuleGeometry args={[.65,.9,8,16]}/><meshStandardMaterial color="#f2c94c"/></mesh></RigidBody>}
function Traffic(){const cars=useMemo(()=>Array.from({length:8},(_,i)=>({x:i%2?2.2:-2.2,z:-55+i*15})),[]);return <>{cars.map((c,i)=><RigidBody key={i} type="fixed" position={[c.x,.6,c.z]}><mesh castShadow><boxGeometry args={[1.7,.9,3.4]}/><meshStandardMaterial color={i%3===0?"#d95d39":"#d8d8d2"}/></mesh></RigidBody>)}</>}
function Scene(){const[hour,setHour]=useState(8);useEffect(()=>{const id=setInterval(()=>setHour(h=>(h+.05)%24),1000);return()=>clearInterval(id)},[]);const night=hour>18||hour<6;return <Canvas shadows><PerspectiveCamera makeDefault position={[0,8,18]} fov={65}/><color attach="background" args={[night?"#07121c":"#8eb4c0"]}/><ambientLight intensity={night?.18:.7}/><directionalLight position={[20,30,10]} intensity={night?0.2:3} castShadow/><Environment preset="city"/><Physics gravity={[0,-9.81,0]}><World night={night}/><Traffic/><Player/></Physics></Canvas>}
export default function Game(){const[money,setMoney]=useState("2500000");const[xp,setXp]=useState(0);const[active,setActive]=useState(missions[0]);const complete=()=>{setMoney(v=>(BigInt(v)+BigInt(active.reward)).toString());setXp(v=>v+active.xp)};const fmt=(v:string)=>{const n=BigInt(v);if(n>=1000000000000000000n)return"₦"+(n/1000000000000000000n)+"Qi";if(n>=1000000000000000n)return"₦"+(n/1000000000000000n)+"Qa";if(n>=1000000000000n)return"₦"+(n/1000000000000n)+"T";if(n>=1000000000n)return"₦"+(n/1000000000n)+"B";if(n>=1000000n)return"₦"+(n/1000000n)+"M";return"₦"+n};return <div><Scene/><div className="hud"><div className="panel"><div className="stats"><div><div className="label">Cash</div><div className="value">{fmt(money)}</div></div><div><div className="label">XP</div><div className="value">{xp}</div></div><div><div className="label">Level</div><div className="value">{Math.floor(xp/500)+1}</div></div></div></div><div className="panel"><div className="label">Mission</div><strong>{active.title}</strong><div>{active.description}</div><button onClick={complete}>Complete +₦{active.reward}</button><div className="hint">{missions[(missions.findIndex(m=>m.id===active.id)+1)%missions.length].title}</div></div></div><div className="controls"><button onClick={()=>setActive(missions[0])}>1</button><button onClick={()=>setActive(missions[1])}>2</button><button onClick={()=>setActive(missions[2])}>3</button></div></div>}
