"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, PerspectiveCamera, Text } from "@react-three/drei";
import { Physics, RigidBody } from "@react-three/rapier";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";

const places = ["🎷 Afrika Shrine","⚽ Viewing Centre","🍲 Amala Shitta","💡 CcHub","🧺 Market","🎭 Freedom Park","🏋️ i-Fitness","🏢 Office","🪩 Quilox","🌉 Canopy Walk","🛍️ The Palms","📚 The Library","🏖️ Beach","🏥 General Hospital","💇🏾‍♀️ Mama Bisi's Salon","🕯️ Ivory Rooftop","🚓 Police Station","⛪ Church","🕌 Mosque","📻 Naija Radio","🗳️ Polling Unit","🏨 Eko Hotels","🚘 Polanco Motors","⛵ Boat Cruise","⛳ Ikoyi Golf Club","⚖️ High Court","🎓 UNILAG","🎰 Eko Casino","🫶🏾 MindSpace","🏟️ Stadium"];
const missions=[{title:"First Day in Lagos",reward:2500,target:[0,25],text:"Meet your first street contact."},{title:"Market Run",reward:15000,target:[-20,-10],text:"Make the delivery before traffic wins."},{title:"Industrial Contract",reward:2500000,target:[30,-55],text:"Deliver cargo to the fictional refinery district."}];
function World(){return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[180,180]}/><meshStandardMaterial color="#65736b"/></mesh><mesh position={[0,.03,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[12,170]}/><meshStandardMaterial color="#202622"/></mesh><mesh position={[0,.04,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[170,12]}/><meshStandardMaterial color="#202622"/></mesh>{Array.from({length:50},(_,i)=><mesh key={i} position={[-70+(i%10)*16,4+((i%5)*1.5),-65+Math.floor(i/10)*28]} castShadow><boxGeometry args={[9,8+(i%5)*2,9]}/><meshStandardMaterial color="#4d5a55"/></mesh>)}<group position={[30,0,-55]}><Text position={[0,12,0]} fontSize={2} color="#e5b943" anchorX="center">INDUSTRIAL ZONE</Text><mesh position={[0,5,0]}><cylinderGeometry args={[5,5,10,24]}/><meshStandardMaterial color="#89958e" metalness={.5}/></mesh></group></group>}
function Player({onMove}:{onMove:(x:number,z:number)=>void}){const ref=useRef<any>(null);const keys=useRef<Record<string,boolean>>({});const last=useRef(0);useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true};const u=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",d);window.addEventListener("keyup",u);return()=>{window.removeEventListener("keydown",d);window.removeEventListener("keyup",u)}},[]);useFrame((state,delta)=>{if(!ref.current)return;const p=ref.current.translation(),k=keys.current;const dx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),dz=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0),len=Math.hypot(dx,dz);if(len>0){const speed=k.shift?16:9,x=THREE.MathUtils.clamp(p.x+dx/len*speed*delta,-82,82),z=THREE.MathUtils.clamp(p.z+dz/len*speed*delta,-82,82);ref.current.setNextKinematicTranslation({x,y:1,z});if(state.clock.elapsedTime-last.current>.1){onMove(x,z);last.current=state.clock.elapsedTime}}const camera=state.camera;camera.position.x=THREE.MathUtils.lerp(camera.position.x,p.x,delta*2);camera.position.z=THREE.MathUtils.lerp(camera.position.z,p.z+18,delta*2);camera.lookAt(p.x,0,p.z)});return <RigidBody ref={ref} type="kinematicPosition" position={[0,1,25]} colliders="cuboid" enabledRotations={[false,false,false]}><mesh castShadow><capsuleGeometry args={[.7,.95,8,16]}/><meshStandardMaterial color="#e5b943"/></mesh></RigidBody>}
function Scene({onMove}:{onMove:(x:number,z:number)=>void}){return <Canvas shadows dpr={[1,1.5]}><PerspectiveCamera makeDefault position={[0,12,40]} fov={58}/><color attach="background" args={["#91afb4"]}/><fog attach="fog" args={["#91afb4",80,150]}/><ambientLight intensity={1}/><directionalLight position={[20,35,10]} intensity={2.5} castShadow/><Environment preset="city"/><Physics gravity={[0,-9.81,0]}><World/><Player onMove={onMove}/></Physics></Canvas>}
function fmt(n:string){const v=BigInt(n);const units=[[1000000000000n,"T"],[1000000000n,"B"],[1000000n,"M"],[1000n,"K"]] as const;for(const item of units)if(v>=item[0])return "₦"+(v/item[0]).toString()+item[1];return "₦"+v}
export default function Game(){const [cash,setCash]=useState("2500000"),[xp,setXp]=useState(0),[mi,setMi]=useState(0),[pos,setPos]=useState({x:0,z:25}),[selected,setSelected]=useState<string|null>(null),[auth,setAuth]=useState(false);const m=missions[mi];const dist=Math.hypot(pos.x-m.target[0],pos.z-m.target[1]);const ready=dist<7;const complete=()=>{if(!ready)return;setCash(v=>(BigInt(v)+BigInt(m.reward)).toString());setXp(v=>v+100);setMi((mi+1)%missions.length)};return <main className="lagosGame"><Scene onMove={(x,z)=>setPos({x,z})}/><header className="topbar"><div className="brand"><b>✦</b><div><strong>Lagos Life</strong><small>live your Lagos story</small></div></div><div className="online">● 163k online now 👀</div><div><button onClick={()=>setAuth(true)}>Sign up</button><button className="ghost" onClick={()=>setAuth(true)}>Log in</button></div></header><aside className="leftRail">{places.map(p=><button key={p} className={selected===p?"place active":"place"} onClick={()=>setSelected(p)}>{p}</button>)}</aside><section className="stats"><span>Cash <b>{fmt(cash)}</b></span><span>Level <b>{Math.floor(xp/500)+1}</b></span><span>XP <b>{xp}</b></span></section><section className="story"><small>ACTIVE HUSTLE</small><h1>{m.title}</h1><p>{m.text}</p><strong>{ready?"MISSION READY":Math.ceil(dist)+"m away"}</strong><button disabled={!ready} onClick={complete}>{ready?"Complete · ₦"+m.reward.toLocaleString():"Explore to continue"}</button></section><div className="mapMini"><b>LAGOS MAP</b><div className="map"><i className="you"/><i className="target"/></div><small>WASD move · Shift sprint · E interact</small></div><nav className="bottomNav">{missions.map((x,i)=><button key={x.title} className={i===mi?"selected":""} onClick={()=>setMi(i)}>{["🏛️","🧺","🚧"][i]} {x.title}</button>)}<button>🌆 Explore</button><button>🏠 Home</button></nav><div className="ticker">🚐 Transport subsidy is law this week · Tap places to explore Lagos · free</div>{selected&&<div className="toast"><button onClick={()=>setSelected(null)}>×</button><b>{selected}</b><p>Explore this Lagos location and discover what happens here.</p></div>}{auth&&<div className="modal"><div><button className="close" onClick={()=>setAuth(false)}>×</button><h2>Live your Lagos story.</h2><p>Create an account to save your character, money, missions and progress.</p><button onClick={()=>setAuth(false)}>Sign up free</button></div></div>}</main>}